name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
      REDIS_URL: ${{secrets.REDIS_URL}}
      GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
      GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
      NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Create env file"
        run: echo "${{ secrets.ENV_FILE }}" > .env
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5 # use the explicit version number
        with:
          build: yarn build
          start: yarn start
